accommodation:
  ownerValue: ownerYAML
  owner:
    name: nameYAML
    facebook: facebookYAML
    instagram: instagramAML

jwt:
  secret: secretAuth

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher